// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_ArcHumid = NULL;lv_obj_t *ui_LabelSetHumid = NULL;lv_obj_t *ui_LabelSetHumidValue = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ArcHumid = lv_arc_create(ui_Screen3);
lv_obj_set_width( ui_ArcHumid, 220);
lv_obj_set_height( ui_ArcHumid, 220);
lv_obj_set_align( ui_ArcHumid, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ArcHumid, 60,90);
lv_arc_set_value(ui_ArcHumid, 70);
lv_arc_set_bg_angles(ui_ArcHumid,130,50);

ui_LabelSetHumid = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_LabelSetHumid, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSetHumid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelSetHumid, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSetHumid,"Настройка\nвлажности");
lv_obj_set_style_text_align(ui_LabelSetHumid, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSetHumid, &ui_font_Font20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSetHumidValue = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_LabelSetHumidValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSetHumidValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSetHumidValue, 0 );
lv_obj_set_y( ui_LabelSetHumidValue, -20 );
lv_obj_set_align( ui_LabelSetHumidValue, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelSetHumidValue,"80%");
lv_obj_set_style_text_align(ui_LabelSetHumidValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSetHumidValue, &ui_font_FontBold25, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
ui_ArcHumid= NULL;
ui_LabelSetHumid= NULL;
ui_LabelSetHumidValue= NULL;

}

void ui_Screen3_screen_relocalize(void)
{
// label widgets on screen

}
