// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_ArcTime = NULL;lv_obj_t *ui_LabelSetTime = NULL;lv_obj_t *ui_LabelSetTimeValue = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ArcTime = lv_arc_create(ui_Screen2);
lv_obj_set_width( ui_ArcTime, 220);
lv_obj_set_height( ui_ArcTime, 220);
lv_obj_set_align( ui_ArcTime, LV_ALIGN_CENTER );
lv_arc_set_range(ui_ArcTime, 5,60);
lv_arc_set_value(ui_ArcTime, 30);
lv_arc_set_bg_angles(ui_ArcTime,130,50);

lv_obj_set_style_arc_color(ui_ArcTime, lv_color_hex(0xC85900), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_ArcTime, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_ArcTime, lv_color_hex(0xFF801A), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ArcTime, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ArcTime, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ArcTime, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ArcTime, 3, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LabelSetTime = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_LabelSetTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSetTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelSetTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSetTime,"Настройка\nтаймера");
lv_obj_set_style_text_align(ui_LabelSetTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSetTime, &ui_font_Font20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSetTimeValue = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_LabelSetTimeValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSetTimeValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSetTimeValue, 0 );
lv_obj_set_y( ui_LabelSetTimeValue, -20 );
lv_obj_set_align( ui_LabelSetTimeValue, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelSetTimeValue,"60 мин");
lv_obj_set_style_text_align(ui_LabelSetTimeValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSetTimeValue, &ui_font_FontBold25, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_ArcTime= NULL;
ui_LabelSetTime= NULL;
ui_LabelSetTimeValue= NULL;

}

void ui_Screen2_screen_relocalize(void)
{
// label widgets on screen

}
