// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_Screen1_screen_relocalize(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_ImageFan;
extern lv_obj_t *ui_ContainerTemp;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_LabelTemp;
extern lv_obj_t *ui_LabelTempValue;
extern lv_obj_t *ui_ContainerHumid;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_LabelHumid;
extern lv_obj_t *ui_LabelHumidValue;
extern lv_obj_t *ui_ContainerMode;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_LabelModeValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

