// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../images/images.h"

extern lv_img_dsc_t *fan_dsc;

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_ImageFan = NULL;lv_obj_t *ui_ContainerTemp = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_LabelTemp = NULL;lv_obj_t *ui_LabelTempValue = NULL;lv_obj_t *ui_ContainerHumid = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_LabelHumid = NULL;lv_obj_t *ui_LabelHumidValue = NULL;lv_obj_t *ui_ContainerMode = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_LabelModeValue = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{

ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImageFan = lv_img_create(ui_Screen1);
if (fan_dsc) lv_img_set_src(ui_ImageFan, fan_dsc);
lv_img_set_src(ui_ImageFan, &fan);
lv_obj_set_width( ui_ImageFan, LV_SIZE_CONTENT);  /// 512
lv_obj_set_height( ui_ImageFan, LV_SIZE_CONTENT);   /// 512
lv_obj_set_align( ui_ImageFan, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ImageFan, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_img_set_angle(ui_ImageFan,9);
lv_img_set_zoom(ui_ImageFan,140);
lv_obj_set_style_img_recolor(ui_ImageFan, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageFan, 150, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerTemp = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_ContainerTemp);
lv_obj_set_width( ui_ContainerTemp, 200);
lv_obj_set_height( ui_ContainerTemp, 72);
lv_obj_set_x( ui_ContainerTemp, 10 );
lv_obj_set_y( ui_ContainerTemp, -40 );
lv_obj_set_align( ui_ContainerTemp, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ContainerTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_ContainerTemp);
lv_img_set_src(ui_Image2, &temperature);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 512
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 512
lv_obj_set_x( ui_Image2, -80 );
lv_obj_set_y( ui_Image2, lv_pct(4) );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,30);

ui_LabelTemp = lv_label_create(ui_ContainerTemp);
lv_obj_set_width( ui_LabelTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTemp, 50 );
lv_obj_set_y( ui_LabelTemp, -13 );
lv_obj_set_align( ui_LabelTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelTemp,"Температура");
lv_obj_set_style_text_font(ui_LabelTemp, &ui_font_Font14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTempValue = lv_label_create(ui_ContainerTemp);
lv_obj_set_width( ui_LabelTempValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTempValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTempValue, 52 );
lv_obj_set_y( ui_LabelTempValue, 13 );
lv_obj_set_align( ui_LabelTempValue, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelTempValue,"--C*");
lv_obj_set_style_text_font(ui_LabelTempValue, &ui_font_FontBold30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerHumid = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_ContainerHumid);
lv_obj_set_width( ui_ContainerHumid, 200);
lv_obj_set_height( ui_ContainerHumid, 72);
lv_obj_set_x( ui_ContainerHumid, 10 );
lv_obj_set_y( ui_ContainerHumid, 30 );
lv_obj_set_align( ui_ContainerHumid, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ContainerHumid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_ContainerHumid);
lv_img_set_src(ui_Image1, &humidity);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 512
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 512
lv_obj_set_x( ui_Image1, -80 );
lv_obj_set_y( ui_Image1, lv_pct(4) );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,30);

ui_LabelHumid = lv_label_create(ui_ContainerHumid);
lv_obj_set_width( ui_LabelHumid, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHumid, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHumid, 50 );
lv_obj_set_y( ui_LabelHumid, -13 );
lv_obj_set_align( ui_LabelHumid, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelHumid,"Влажность");
lv_obj_set_style_text_font(ui_LabelHumid, &ui_font_Font14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHumidValue = lv_label_create(ui_ContainerHumid);
lv_obj_set_width( ui_LabelHumidValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHumidValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHumidValue, 52 );
lv_obj_set_y( ui_LabelHumidValue, 13 );
lv_obj_set_align( ui_LabelHumidValue, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_LabelHumidValue,"--%");
lv_obj_set_style_text_font(ui_LabelHumidValue, &ui_font_FontBold30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerMode = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_ContainerMode);
lv_obj_set_width( ui_ContainerMode, 100);
lv_obj_set_height( ui_ContainerMode, 33);
lv_obj_set_x( ui_ContainerMode, 0 );
lv_obj_set_y( ui_ContainerMode, 90 );
lv_obj_set_align( ui_ContainerMode, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ContainerMode, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_ContainerMode);
lv_obj_set_width( ui_Panel1, 83);
lv_obj_set_height( ui_Panel1, 30);
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFF7200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelModeValue = lv_label_create(ui_ContainerMode);
lv_obj_set_width( ui_LabelModeValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelModeValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelModeValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelModeValue,"ручной");
lv_obj_set_style_text_font(ui_LabelModeValue, &ui_font_FontBold16, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_ImageFan= NULL;
ui_ContainerTemp= NULL;
ui_Image2= NULL;
ui_LabelTemp= NULL;
ui_LabelTempValue= NULL;
ui_ContainerHumid= NULL;
ui_Image1= NULL;
ui_LabelHumid= NULL;
ui_LabelHumidValue= NULL;
ui_ContainerMode= NULL;
ui_Panel1= NULL;
ui_LabelModeValue= NULL;

}

void ui_Screen1_screen_relocalize(void)
{
// label widgets on screen

}
