// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

    #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1939720481);   // assets/free-icon-fan-9021434.png
LV_IMG_DECLARE( ui_img_2122670701);   // assets/free-icon-temperature-2652881.png
LV_IMG_DECLARE( ui_img_1360404416);   // assets/free-icon-humidity-6126308.png
LV_IMG_DECLARE( ui_img_277349689);   // assets/QR-code IP.png
LV_IMG_DECLARE( ui_img_377560965);   // assets/left-arrow-angle-big-gross-symbol.png

// FONTS
LV_FONT_DECLARE( ui_font_Font14);
LV_FONT_DECLARE( ui_font_Font12);
LV_FONT_DECLARE( ui_font_Font10);
LV_FONT_DECLARE( ui_font_Font16);
LV_FONT_DECLARE( ui_font_Font20);
LV_FONT_DECLARE( ui_font_FontBold30);
LV_FONT_DECLARE( ui_font_Font18);
LV_FONT_DECLARE( ui_font_FontBold16);
LV_FONT_DECLARE( ui_font_FontBold14);
LV_FONT_DECLARE( ui_font_FontBold25);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
